// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/projects/data": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "Display of all projects registered in taiga",
                "responses": {}
            }
        },
        "/statistics/data/{id}": {
            "get": {
                "description": "This endpoint displays all projects based on date range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistics"
                ],
                "summary": "Display of all projects registered in taiga",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id do projeto para busca",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2025-04-01\"",
                        "description": "Data de início (formato: YYYY-MM-DD)",
                        "name": "data1",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"2025-04-30\"",
                        "description": "Data de fim (formato: YYYY-MM-DD)",
                        "name": "data2",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
