-- Drop schema named "public"
-- DROP SCHEMA "dw" CASCADE;
-- Add new schema named "dw"
CREATE SCHEMA "dw";
-- Create "dim_platform" table
CREATE TABLE "dw"."dim_platform" (
  "id_platform" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_platform" character varying(200) NOT NULL,
  PRIMARY KEY ("id_platform")
);
-- Create "dim_project" table
CREATE TABLE "dw"."dim_project" (
  "id_project" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_project" character varying(200) NOT NULL,
  "description" character varying(400) NOT NULL,
  "id_platform" integer NOT NULL,
  PRIMARY KEY ("id_project"),
  CONSTRAINT "dim_project_id_platform_fkey" FOREIGN KEY ("id_platform") REFERENCES "dw"."dim_platform" ("id_platform") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "dim_day" table
CREATE TABLE "dw"."dim_day" (
  "id_day" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "day" integer NOT NULL,
  PRIMARY KEY ("id_day")
);
-- Create "dim_hour" table
CREATE TABLE "dw"."dim_hour" (
  "id_hour" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "hour" integer NOT NULL,
  PRIMARY KEY ("id_hour")
);
-- Create "dim_minute" table
CREATE TABLE "dw"."dim_minute" (
  "id_minute" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "minute" integer NOT NULL,
  PRIMARY KEY ("id_minute")
);
-- Create "dim_month" table
CREATE TABLE "dw"."dim_month" (
  "id_month" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "month" integer NOT NULL,
  PRIMARY KEY ("id_month")
);
-- Create "dim_year" table
CREATE TABLE "dw"."dim_year" (
  "id_year" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "year" integer NOT NULL,
  PRIMARY KEY ("id_year")
);
-- Create "dim_time" table
CREATE TABLE "dw"."dim_time" (
  "id_time" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "date" date NOT NULL,
  "id_day" integer NOT NULL,
  "id_month" integer NOT NULL,
  "id_year" integer NOT NULL,
  "id_hour" integer NOT NULL,
  "id_minute" integer NOT NULL,
  PRIMARY KEY ("id_time"),
  CONSTRAINT "dim_time_id_day_fkey" FOREIGN KEY ("id_day") REFERENCES "dw"."dim_day" ("id_day") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "dim_time_id_hour_fkey" FOREIGN KEY ("id_hour") REFERENCES "dw"."dim_hour" ("id_hour") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "dim_time_id_minute_fkey" FOREIGN KEY ("id_minute") REFERENCES "dw"."dim_minute" ("id_minute") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "dim_time_id_month_fkey" FOREIGN KEY ("id_month") REFERENCES "dw"."dim_month" ("id_month") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "dim_time_id_year_fkey" FOREIGN KEY ("id_year") REFERENCES "dw"."dim_year" ("id_year") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "dim_role" table
CREATE TABLE "dw"."dim_role" (
  "id_role" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_role" character varying(200) NOT NULL,
  PRIMARY KEY ("id_role")
);
-- Create "dim_user" table
CREATE TABLE "dw"."dim_user" (
  "id_user" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_user" character varying(200) NOT NULL,
  "email" character varying(200) NOT NULL,
  "password" character varying(400) NULL,
  "id_role" integer NOT NULL,
  PRIMARY KEY ("id_user"),
  CONSTRAINT "dim_user_id_role_fkey" FOREIGN KEY ("id_role") REFERENCES "dw"."dim_role" ("id_role") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "dim_card" table
CREATE TABLE "dw"."dim_card" (
  "id_card" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_card" character varying(200) NOT NULL,
  "description" character varying(400) NOT NULL,
  PRIMARY KEY ("id_card")
);
-- Create "dim_status" table
CREATE TABLE "dw"."dim_status" (
  "id_status" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_status" character varying(200) NOT NULL,
  PRIMARY KEY ("id_status")
);
-- Create "dim_tag" table
CREATE TABLE "dw"."dim_tag" (
  "id_tag" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_tag" character varying(200) NOT NULL,
  PRIMARY KEY ("id_tag")
);
-- Create "fato_cards" table
CREATE TABLE "dw"."fato_cards" (
  "id_fato_card" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "id_card" integer NOT NULL,
  "id_project" integer NOT NULL,
  "id_user" integer NOT NULL,
  "id_status" integer NOT NULL,
  "id_time" integer NOT NULL,
  "id_tag" integer NULL,
  "qtd_cards" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id_fato_card"),
  CONSTRAINT "fato_cards_id_card_fkey" FOREIGN KEY ("id_card") REFERENCES "dw"."dim_card" ("id_card") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fato_cards_id_project_fkey" FOREIGN KEY ("id_project") REFERENCES "dw"."dim_project" ("id_project") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fato_cards_id_status_fkey" FOREIGN KEY ("id_status") REFERENCES "dw"."dim_status" ("id_status") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fato_cards_id_tag_fkey" FOREIGN KEY ("id_tag") REFERENCES "dw"."dim_tag" ("id_tag") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fato_cards_id_time_fkey" FOREIGN KEY ("id_time") REFERENCES "dw"."dim_time" ("id_time") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fato_cards_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "dw"."dim_user" ("id_user") ON UPDATE NO ACTION ON DELETE NO ACTION
);
