name: Go Code Check

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
      - 'develop/*'

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Clean Go Cache
        run: go clean -cache -modcache -testcache -x

      - name: Install Dependencies
        working-directory: src
        run: go mod download

      - name: Run Go Format
        working-directory: src
        run: go fmt $(go list ./... | grep -v /vendor/)

      - name: Run Go Mod Tidy
        working-directory: src
        run: go mod tidy

      - name: Run GolangCI-Lint
        working-directory: src
        run: golangci-lint run