name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main
      - sprint-1
      - sprint-2
      - sprint-3
      - 'feature/**' # Adicionando feature branches
      - 'fix/**' # Adicionando fix branches
      - 'hotfix/**' # Adicionando hotfix branches
      - 'release/**' # Adicionando release branches

jobs:
  sonarqube-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para análise correta no Sonar

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: src

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=src
            -Dsonar.go.coverage.reportPaths=coverage.out
